language: ruby
rvm:
- 2.5.1
sudo: false
script: bundle exec rake deploy
before_install:
  - gem update --system
env:
  global:
    secure: J+oFCA3BXEWUA2j+YzeKDNRZ+Ul3/i5ef3DDM6EmKuFdu7+fqtnfkEN/fxzD4urqKrCYWUeH+b1xZvD9kTNI+jGSPkUMACwz1RMG5PFHVGZSiBgET4yK+U4RZ35sesK4EPIXbl9l6tpgF9kUTRDZlP7nGEEes94NI+h1SxiSqwxRd5I5sAcsJNseNipL09S+R+fTpjsFU5KXEGpwrbvg54D6U97D3w/NPdvvWky2fMtsDV3gYtBejmM8ZF9o2NVWpvd56w5l8hKXK3K8wfNTJkINDgi0792bkPDkiPc4j1tOXpBij0+osmhysLSTND5n2fIQSuA+w/r7b9oJ3DQMM3RLjcd0/tvzENWu1WcVZBEO4ae8yk9D6AgAGymZXpNONd6B3RaOzyziP+xTXjfOHnFlq7dZIvHwIEMM5aRL4ShGcWY5JF1Xju5/wrFFGh72sFrWGjgVHAkbiNTK+qQ4aTIHkH2RblG3yL9xYmO+mN4TmTAQIDtGvb4aVvzmmo2TdAX8lgU08ocMs1lO+GzJmbKoVk57XRrINUeNQdabgvEDLt485YFywkqgjF+JYVRQLan/Ty7iHLAETVhpIFbk394d2U91dDoeh7F0EN7mvoY5ERBL9XvQNmMddG2I9g69i0rLF5Y3I6ZC7D0cvdFr0lQyAbGD/kRHlp4Hv+iEJDM=
